### ISSUE TITLE
Linking against custom Boost installation

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/PyBDSF#106]
Hi,

We have our own installation of Boost (1.63.0) alongside the system default (1.53.0) and I'm trying to get PyBDSF to link against that newer version instead of the system installed version, but it always seems to pick up the system default. Is there a way to do this? (we cannot upgrade the system version)

I have tried setting
```
export LD_LIBRARY_PATH=${INSTALLDIR}/boost/lib
```
and also
```
python setup.py build_ext -L{$INSTALLDIR}/boost/lib
python setup.py install --prefix=${INSTALLDIR}/pybdsf/
```
but to no avail.

I can force it to load my Boost version with
```
export LD_PRELOAD=${INSTALLDIR}/boost/lib/libboost_python.so
```
but that results in an `undefined symbol: PyExc_ValueError` being thrown by other commands during build.

**Comment by 1054** [comment]
Probably you can try [Conda](https://docs.conda.io/en/latest/miniconda.html) and follow #105's solution to see if it works for you or not? I think Conda does not require root permission, and provides isolated environments (e.g., Python, gcc, libboost) with everything installed into your home directory. This solves a lot of compatible issue.

**Comment by MatthewJA** [comment]
I got this working recently, but it required hacking `setup.py` — there's some hard-coded references in there to versions of libboost that aren't entirely correct. Then the setup calls `ctypes.find_library`. So if you can find your libboost with `find_library` and make that the library that `setup.py` searches for, it should all work.

**Comment by gmloose** [comment]
I'm closing this issue, since it's three years old. Feel free to open a new issue if you still encounter problems.
