### ISSUE TITLE
PIP package out of date

### ISSUE THREAD

**Issue by o-smirnov** [lofar-astron/PyBDSF#109]
As described here: https://github.com/kernsuite/packaging/issues/210

**Comment by o-smirnov** [comment]
Hmmm, I see I already reported this in #102...

**Comment by tammojan** [comment]
@o-smirnov The erorr you report in kernsuite/packaging#210 looks like you're missing `gfortran`. Maybe building from source will work around the pip package being out of date; I'll try to update it soon.

**Comment by tammojan** [comment]
I just released a new version to pip.
