### ISSUE TITLE
ValueError: axes don't match array

### ISSUE THREAD

**Issue by epolisensky** [lofar-astron/PyBDSF#112]
Anybody seen this error message before? Full message is:

  File "/usr/local/lib/python3.6/dist-packages/bdsf/functions.py", line 1343, in read_image_from_file
    data = data.transpose(*indx_out) # transpose axes to final order
ValueError: axes don't match array

It's something specific to the image as I'm able to run other images fine (PyBDSF v1.9.1). But there's nothing apparently unusual about the image.

**Comment by epolisensky** [comment]
Solved it. This is caused by a non-standard CTYPE used for the 3rd axis. PyBDSF can't figure out it's FREQ so indx_out does not get set properly. 

Hopefully this saves someone else a headache someday.

**Comment by mckabuza** [comment]
Hi epolisensky, I am also getting the same error as above. How did you actually go on about solving it?

**Comment by epolisensky** [comment]
I used astropy to change CTYPE3 to 'FREQ' and wrote a new fits file
