### ISSUE TITLE
compilation fails with _IO_stderr undeclared 

### ISSUE THREAD

**Issue by nzasch** [lofar-astron/PyBDSF#119]
Hi

compiling PyBDSF v 1.9.2 on a Centos 8  shipping GCC 8.3.1 and glibc 2.28-72 fails with error:

    building 'bdsf.nat.natgridmodule' extension
    compiling C sources
    C compiler: gcc -pthread -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -w -fPIC

    creating build/temp.linux-x86_64-3.6/natgrid
    creating build/temp.linux-x86_64-3.6/natgrid/Src
    compile options: '-Inatgrid/Include -I/opt/numpy/lib64/python3.6/site-packages/numpy/core/include -I/opt/OpenBLAS/include -I/opt/boost/include -I/usr/include/python3.6m -c'
    gcc: natgrid/Src/nnuser.c
    gcc: natgrid/Src/nnerror.c
    gcc: natgrid/Src/nnusers.c
    gcc: natgrid/Src/nncrunchd.c
    gcc: natgrid/Src/nnuserd.c
    gcc: natgrid/Src/nncrunchs.c
    gcc: natgrid/Src/natgrids.c
    gcc: natgrid/Src/nncrunch.c
    gcc: natgrid/Src/natgridmodule.c
    gcc: natgrid/Src/natgridd.c
    gcc: natgrid/Src/natgrid.c
    In file included from natgrid/Src/natgrid.c:6:
    natgrid/Include/nnmhead.h:43:28: error: ‘_IO_stderr’ undeclared here (not in a function); did you mean ‘stderr’?
     FILE    *fopen(), *filee = _IO_stderr;
                                ^~~~~~~~~~
                                stderr
    error: Command "gcc -pthread -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -w -fPIC -Inatgrid/Include -I/opt/numpy/lib64/python3.6/site-packages/numpy/core/include -I/opt/OpenBLAS/include -I/opt/boost/include -I/usr/include/python3.6m -c natgrid/Src/natgrid.c -o build/temp.linux-x86_64-3.6/natgrid/Src/natgrid.o -MMD -MF build/temp.linux-x86_64-3.6/natgrid/Src/natgrid.o.d" failed with exit status 1
Cleaning up...
  Removing source in /tmp/pip-lhwie8h7-build
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-lhwie8h7-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext -I/opt/OpenBLAS/include:/opt/boost/include -L/opt/OpenBLAS/lib:/opt/boost/lib install --record /tmp/pip-yvk790zv-record/install-record.txt --single-version-externally-managed --compile --prefix=/opt/pybdsf-1.9.2" failed with error code 1 in /tmp/pip-lhwie8h7-build/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 882, in install
    spinner=spinner,
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 717, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-lhwie8h7-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext -I/opt/OpenBLAS/include:/opt/boost/include -L/opt/OpenBLAS/lib:/opt/boost/lib install --record /tmp/pip-yvk790zv-record/install-record.txt --single-version-externally-managed --compile --prefix=/opt/pybdsf-1.9.2" failed with error code 1 in /tmp/pip-lhwie8h7-build/

many thanks

**Comment by mhardcastle** [comment]
This is a problem for both gcc 7 and 8. There is a simple fix, just to skip the `#ifdef linux` branch. I have a PR to fix it...
