### ISSUE TITLE
python3 building against 2.7 libboost

### ISSUE THREAD

**Issue by cyriltasse** [lofar-astron/PyBDSF#131]
Weird problem I'm building pybdsf in a python3 venv, it finds `boost_python-py36`, but when importing `bdsf`:

`ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1: undefined symbol: PyClass_Type`

So it's built against `boost2.7`... and `ldd` gives

```
(VE_Py3_fs06) sttf310@fs06:~/VE_Py3_fs06/sources/PyBDSF$ ldd ./build/lib.linux-x86_64-3.6/bdsf/_cbdsm.cpython-36m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffc781cc000)
	libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f75b3bab000)
	libboost_python3-py36.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_python3-py36.so.1.65.1 (0x00007f75b396c000)
	libboost_numpy-py27.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_numpy-py27.so.1.65.1 (0x00007f75b3761000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f75b33d8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f75b303a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f75b2e22000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f75b2a31000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f75b27f1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f75b25d2000)
	libboost_python-py27.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1 (0x00007f75b2392000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f75b41d6000)
```

Any idea?

**Comment by cyriltasse** [comment]
I noted the installed numpy boot where:

```
/usr/lib/x86_64-linux-gnu/libboost_numpy3.a
/usr/lib/x86_64-linux-gnu/libboost_numpy3-py36.a
/usr/lib/x86_64-linux-gnu/libboost_numpy3-py36.so
/usr/lib/x86_64-linux-gnu/libboost_numpy3-py36.so.1.65.1
/usr/lib/x86_64-linux-gnu/libboost_numpy3.so
/usr/lib/x86_64-linux-gnu/libboost_numpy.a
/usr/lib/x86_64-linux-gnu/libboost_numpy-py27.a
/usr/lib/x86_64-linux-gnu/libboost_numpy-py27.so
/usr/lib/x86_64-linux-gnu/libboost_numpy-py27.so.1.65.1
/usr/lib/x86_64-linux-gnu/libboost_numpy.so
```

so I added `boost_numpy3-py' + short_version,` to the list `boostlibnames` here: 

https://github.com/lofar-astron/PyBDSF/blob/e1cacb7f6601f3b287a00a8ec77808d62bca8fab/setup.py#L146

and that fixes it... I don't know how these things are supposed to work, but you might want to update master eventually?

**Comment by cyriltasse** [comment]
I'm surprised nobody ran into this before...

**Comment by tammojan** [comment]
Thanks for reporting @cyriltasse! Finding a boost is always tricky since the library name differs between distributions / operating systems. Could you try if pull request #132 works for you?

**Comment by cyriltasse** [comment]
Hey @tammojan  - yes - that branch is working for me! thanks!

**Comment by Mora-max** [comment]
> I noted the installed numpy boot where:
> 
> ```
> /usr/lib/x86_64-linux-gnu/libboost_numpy3.a
> /usr/lib/x86_64-linux-gnu/libboost_numpy3-py36.a
> /usr/lib/x86_64-linux-gnu/libboost_numpy3-py36.so
> /usr/lib/x86_64-linux-gnu/libboost_numpy3-py36.so.1.65.1
> /usr/lib/x86_64-linux-gnu/libboost_numpy3.so
> /usr/lib/x86_64-linux-gnu/libboost_numpy.a
> /usr/lib/x86_64-linux-gnu/libboost_numpy-py27.a
> /usr/lib/x86_64-linux-gnu/libboost_numpy-py27.so
> /usr/lib/x86_64-linux-gnu/libboost_numpy-py27.so.1.65.1
> /usr/lib/x86_64-linux-gnu/libboost_numpy.so
> ```
> 
> so I added `boost_numpy3-py' + short_version,` to the list `boostlibnames` here:
> 
> https://github.com/lofar-astron/PyBDSF/blob/e1cacb7f6601f3b287a00a8ec77808d62bca8fab/setup.py#L146
> 
> and that fixes it... I don't know how these things are supposed to work, but you might want to update master eventually?

could you please explain how did you solve it?! 
thank you.

**Comment by tammojan** [comment]
The original problem should be solved if you update to the latest master.
