### ISSUE TITLE
AttributeError: module '__main__' has no attribute '__spec__' while running process_image

### ISSUE THREAD

**Issue by Joegrundy0001** [lofar-astron/PyBDSF#137]
During gaussian fitting I receive an attribute error. I am using MacOS 10.11.6 and installed using the method described in issue #104.

BDSF [4]: go
--------> go()
--> Opened '1904-66_SIN.fits'
Image size .............................. : (192, 192) pixels
Number of channels ...................... : 1
Number of Stokes parameters ............. : 1
Beam shape (major, minor, pos angle) .... : (2.40000e-01, 2.40000e-01, 0.0) degrees
Frequency of image ...................... : 1420.000 MHz
Number of blank pixels .................. : 14837 (40.2%)
Flux from sum of (non-blank) pixels ..... : 43.283 Jy
--> Calculating background rms and mean images
Derived rms_box (box size, step size) ... : (51, 17) pixels
--> Size of rms_box larger than 1/4 of image size
--> Using constant background rms and mean
Value of background rms ................. : 6.61e-02 Jy/beam
Value of background mean ................ : -0.02063 Jy/beam
--> Expected 5-sigma-clipped false detection rate < fdr_ratio
--> Using sigma-clipping ('hard') thresholding
Minimum number of pixels per island ..... : 6
Number of islands found ................. : 46
Fitting islands with Gaussians .......... : [---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/opt/anaconda3/envs/aegean/lib/python3.8/site-packages/bdsf-1.9.2-py3.8-macosx-10.9-x86_64.egg/EGG-INFO/scripts/pybdsf in <module>
----> 1 go()

/opt/anaconda3/envs/aegean/lib/python3.8/site-packages/bdsf-1.9.2-py3.8-macosx-10.9-x86_64.egg/EGG-INFO/scripts/pybdsf in go(cur_cmd)
     77         print('\033[31;1mERROR\033[0m: not a valid task')
     78         return
---> 79     cur_cmd()
     80 
     81 

/opt/anaconda3/envs/aegean/lib/python3.8/site-packages/bdsf-1.9.2-py3.8-macosx-10.9-x86_64.egg/EGG-INFO/scripts/pybdsf in process_image(**kwargs)
    364     # from the Image object, so we don't need to get_task_kwargs as
    365     # we do for the other tasks.
--> 366     success = _img.process(**kwargs)
    367 
    368     # Now restore parameters and save to pybdsf.last

/opt/anaconda3/envs/aegean/lib/python3.8/site-packages/bdsf-1.9.2-py3.8-macosx-10.9-x86_64.egg/bdsf/image.py in process(self, **kwargs)
    133         """Process Image object"""
    134         from . import interface
--> 135         success = interface.process(self, **kwargs)
    136         return success
    137 

/opt/anaconda3/envs/aegean/lib/python3.8/site-packages/bdsf-1.9.2-py3.8-macosx-10.9-x86_64.egg/bdsf/interface.py in process(img, **kwargs)
     60         img, op_chain = get_op_chain(img)
     61         if op_chain is not None:
---> 62             _run_op_list(img, op_chain)
     63             img._prev_opts = img.opts.to_dict()
     64         return True

/opt/anaconda3/envs/aegean/lib/python3.8/site-packages/bdsf-1.9.2-py3.8-macosx-10.9-x86_64.egg/bdsf/__init__.py in _run_op_list(img, chain)
    150                 answ = raw_input_no_history(prompt)
    151         op.__start_time = time()
--> 152         op(img)
    153         op.__stop_time = time()
    154         gc.collect()

/opt/anaconda3/envs/aegean/lib/python3.8/site-packages/bdsf-1.9.2-py3.8-macosx-10.9-x86_64.egg/bdsf/gausfit.py in __call__(self, img)
     93         # Now call the parallel mapping function. Returns a list of [gaul, fgaul]
     94         # for each island.
---> 95         gaus_list = mp.parallel_map(func.eval_func_tuple,
     96                     zip(itertools.repeat(self.process_island),
     97                     img.islands, itertools.repeat(img_simple),

/opt/anaconda3/envs/aegean/lib/python3.8/site-packages/bdsf-1.9.2-py3.8-macosx-10.9-x86_64.egg/bdsf/multi_proc.py in parallel_map(function, sequence, numcores, bar, weights)
    174     # to a spawned child process and has methods which will create shared
    175     # objects and return corresponding proxies.
--> 176     manager = multiprocessing.Manager()
    177 
    178     # Create FIFO queue and lock shared objects and return proxies to them.

/opt/anaconda3/envs/aegean/lib/python3.8/multiprocessing/context.py in Manager(self)
     55         from .managers import SyncManager
     56         m = SyncManager(ctx=self.get_context())
---> 57         m.start()
     58         return m
     59 

/opt/anaconda3/envs/aegean/lib/python3.8/multiprocessing/managers.py in start(self, initializer, initargs)
    577         ident = ':'.join(str(i) for i in self._process._identity)
    578         self._process.name = type(self).__name__  + '-' + ident
--> 579         self._process.start()
    580 
    581         # get address of server

/opt/anaconda3/envs/aegean/lib/python3.8/multiprocessing/process.py in start(self)
    119                'daemonic processes are not allowed to have children'
    120         _cleanup()
--> 121         self._popen = self._Popen(self)
    122         self._sentinel = self._popen.sentinel
    123         # Avoid a refcycle if the target function holds an indirect

/opt/anaconda3/envs/aegean/lib/python3.8/multiprocessing/context.py in _Popen(process_obj)
    282         def _Popen(process_obj):
    283             from .popen_spawn_posix import Popen
--> 284             return Popen(process_obj)
    285 
    286     class ForkServerProcess(process.BaseProcess):

/opt/anaconda3/envs/aegean/lib/python3.8/multiprocessing/popen_spawn_posix.py in __init__(self, process_obj)
     30     def __init__(self, process_obj):
     31         self._fds = []
---> 32         super().__init__(process_obj)
     33 
     34     def duplicate_for_child(self, fd):

/opt/anaconda3/envs/aegean/lib/python3.8/multiprocessing/popen_fork.py in __init__(self, process_obj)
     17         self.returncode = None
     18         self.finalizer = None
---> 19         self._launch(process_obj)
     20 
     21     def duplicate_for_child(self, fd):

/opt/anaconda3/envs/aegean/lib/python3.8/multiprocessing/popen_spawn_posix.py in _launch(self, process_obj)
     40         tracker_fd = resource_tracker.getfd()
     41         self._fds.append(tracker_fd)
---> 42         prep_data = spawn.get_preparation_data(process_obj._name)
     43         fp = io.BytesIO()
     44         set_spawning_popen(self)

/opt/anaconda3/envs/aegean/lib/python3.8/multiprocessing/spawn.py in get_preparation_data(name)
    181     # or through direct execution (or to leave it alone entirely)
    182     main_module = sys.modules['__main__']
--> 183     main_mod_name = getattr(main_module.__spec__, "name", None)
    184     if main_mod_name is not None:
    185         d['init_main_from_name'] = main_mod_name

AttributeError: module '__main__' has no attribute '__spec__'

**Comment by SimonP2207** [comment]
I'll second this as having the same issue, and I'm using MacOS (10.14.6) and also used #104 for my installation. The multiprocessing module doesn't appear to play nicely with the interactive iPython console... Any further in solving this?

**Comment by darafferty** [comment]
Unfortunately, I haven't been able to reproduce this problem on my Mac (MacOS 11.2.1, using Anaconda and Python 3.7.6). I will try to see if I can get access to one with MacOS 10.x and/or Python 3.8.

**Comment by gmloose** [comment]
Is this still an issue?

**Comment by Joegrundy0001** [comment]
I don't know as I have moved to using a different program on a linux system.

**Comment by gmloose** [comment]
Then I'll close it for now. Please re-open it (or create an new issue) if you run into issues again.
