### ISSUE TITLE
fails on some installations if GDK cannot connect to an X-server

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/PyBDSF#14]
On some installations `import matplotlib.pyplot as pl` fails if GDK cannot connect to an X-server. (Not on any machines that I have easy access to, so I cannot really test it.)
PyBDSM doesn't require `matplotlib` all the time, so it already has code to continue if `matplotlib` is not available. Unfortunately this code doesn't seem to catch the problem with GDK.

Could this issue be solved by simply adding `AssertionError` to line 14 of  `PyBDSF/bdsf/__init__.py`?

**Comment by darafferty** [comment]
Sounds like it should work, so I added the `AssertionError` as suggested. Let's see if it solves the problem (I don't a way to test it either).
