### ISSUE TITLE
ImportError PyClass_Type

### ISSUE THREAD

**Issue by DominikRh** [lofar-astron/PyBDSF#143]
Dear authors,

I am trying to make pybdsf work with Python 3. I installed it with pip using `python3 -m pip install https://github.com/lofar-astron/PyBDSF/archive/v1.9.2.tar.gz`; the installation seems to have worked fine, but if I try to import the bdsf module, I get the following error: 
`ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1: undefined symbol: PyClass_Type`

I have already figured out that this has to do with the boost libraries; here are the dependencies:

        ldd _cbdsm.cpython-36m-x86_64-linux-gnu.so

        linux-vdso.so.1 (0x00007ffd7c1a7000)
        libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f1f3129c000)
        libboost_python3-py36.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_python3-py36.so.1.65.1 (0x00007f1f3105d000)
        libboost_numpy-py27.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_numpy-py27.so.1.65.1 (0x00007f1f30e52000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1f30ac9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1f3072b000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1f30513000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1f30122000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f1f2fee2000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1f2fcc3000)
        libboost_python-py27.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1 (0x00007f1f2fa83000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1f318c7000)`

I have the following libboost libraries on my computer; for libboost_python:

    libboost_python-py36.so
    libboost_python-py27.so
    libboost_python-py27.so.1.65.1
    libboost_python3.so
    libboost_python3-py36.so.1.65.1
    libboost_python3-py36.so

And for libboost_numpy:

    /usr/lib/x86_64-linux-gnu/libboost_numpy3.a               /usr/lib/x86_64-linux-gnu/libboost_numpy.a
    /usr/lib/x86_64-linux-gnu/libboost_numpy3-py36.a          /usr/lib/x86_64-linux-gnu/libboost_numpy-py27.a
    /usr/lib/x86_64-linux-gnu/libboost_numpy3-py36.so         /usr/lib/x86_64-linux-gnu/libboost_numpy-py27.so
    /usr/lib/x86_64-linux-gnu/libboost_numpy3-py36.so.1.65.1  /usr/lib/x86_64-linux-gnu/libboost_numpy-py27.so.1.65.1
    /usr/lib/x86_64-linux-gnu/libboost_numpy3.so              /usr/lib/x86_64-linux-gnu/libboost_numpy.so

I have also looked up other closed issue discussions, and this one looks like the same issue:
https://github.com/lofar-astron/PyBDSF/issues/131
From what I can tell, it seems to me that switching up the order in which the different possible boost names are tested in setup.py to start with "numpy3" would be a good idea. I, however, have no experience with manually compiling python packages, so can somebody please help me make this work?

**Comment by gmloose** [comment]
You can install the latest release from pypi.org. For linux there are binary wheels for Python 3.6..3.10.

Just type `pip install --upgrade bdsf`. This should pull and install latest release as binary wheel.
