### ISSUE TITLE
PEP 517 install time dependencies

### ISSUE THREAD

**Issue by bennahugo** [lofar-astron/PyBDSF#148]
At the moment bdsf tries to import numpy as a setup.py import. This needs to be specified
as a compile time dependency to for pip to install prior to running setup.py (see PEP 517)

**Comment by bennahugo** [comment]
An example is here:
https://github.com/saopicc/DDFacet/blob/master/pyproject.toml

**Comment by gabicca** [comment]
I think I have this problem, trying to install bdsf on python3.8: 

```
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-resolver-ilrqlqyg/bdsf/setup.py", line 7, in <module>
          from numpy.distutils.core import setup
      ModuleNotFoundError: No module named 'numpy'
```

I see that this issue has been opened a month ago. Any updates on when this may be resolved?

**Comment by tammojan** [comment]
This issue should not prevent you from installing pybdsf. Simply install numpy before installing pybdsf. I hadn't heard of pep517 before, we will add this at some point.

**Comment by gabicca** [comment]
I know we can solve it that way, but the situation is very far from ideal. So I was wondering if there's a plan to fix it.

**Comment by bennahugo** [comment]
I've tested the fix locally in a fresh venv. This now installs without further user input. It also means any package depending on bdsf (e.g. DDFacet for us) will just install seamlessly without the user having to install package by package any setup dependency issues. Note there is still #149 @tammojan, could you please comment?

**Comment by tammojan** [comment]
Thanks @bennahugo! I've commented to #149.

**Comment by gabicca** [comment]
Thank you both!!
