### ISSUE TITLE
Missing install dependencies

### ISSUE THREAD

**Issue by bennahugo** [lofar-astron/PyBDSF#149]
Currently the following dependencies are missing:
 - matplotlib
 - astropy
 - ipython

perhaps some of these can be specified as optional-requires?

**Comment by tammojan** [comment]
Astropy should be a hard requirement, as pybdsf needs fits, and pyfits was replaced by astropy.io.fits.

I think matplotlib is really optional, and I hope ipython is also optional, could you confirm @darafferty?. Another optional-requires is python-casacore.

**Comment by darafferty** [comment]
Yes, you're right -- matplotlib and ipython are both optional.

**Comment by gmloose** [comment]
This has been fixed some time ago, already. Check the latest release (1.10.1).
