### ISSUE TITLE
Attribute Error no get_history

### ISSUE THREAD

**Issue by Joshuaalbert** [lofar-astron/PyBDSF#15]
I'm using pdbdsm-1.8.7 and for two fits files made with casa it works fine, but for a third also made with the same casa I get `AttributeError: 'Header' object has no attribute 'get_history'`. The only difference between the fits files is that the first two were made with multiscale and the first two were not. It's getting stuck in readimage.py line 380, 
```
### try see if AIPS as put the beam in HISTORY as usual
for h in hdr.get_history():
...
```

**Comment by tammojan** [comment]
This was reported already as #12, and should have been fixed in 1065c046763e8bc67881e84ffe585a2c56ab6a6f , which is not yet in any release.
