### ISSUE TITLE
Installation successful but cannot import bdsf

### ISSUE THREAD

**Issue by aishrimc** [lofar-astron/PyBDSF#156]
After installing PyBDSF using `pip install https://github.com/lofar-astron/PyBDSF/archive/v1.9.1.tar.gz` successfully, doing `import bdsf` in IPython console is giving the error `ImportError: /home/amc/.local/lib/python3.8/site-packages/bdsf/_cbdsm.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE` followed by `libgcc_s.so.1 must be installed for pthread_cancel to work` and there is core dumping. If it a Python console (instead of IPython), or if I type `pybdsf` in the terminal to launch the it, only the import error i.e. `ImportError: /home/aishrila/.local/lib/python3.8/site-packages/bdsf/_cbdsm.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE` is occuring, i.e. there is no core dump.
The machine uses Anaconda3 and libgcc_s.so.1 is there in `/home/amc/anaconda3/pkgs/libgcc-ng-9.1.0-hdf63c60_0/lib/`. It is a CentOS 7 machine. 
Also this problem is persisting even for `pip install --user https://github.com/lofar-astron/PyBDSF/archive/v1.9.1.tar.gz`. Any suggestions on how to work around this would be helpful. Thank you.

**Comment by gmloose** [comment]
Please reinstall using `pip`. Binary wheels are now available for python 3.6..3.10 on linux.
