### ISSUE TITLE
Hanging for very large island

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/PyBDSF#158]
We use PyBDSF to help make the mask in the early stages of ddf-pipeline. This has been fine for normal extragalactic fields, but for Galactic fields (and possibly with the rms maps provided by Cyril's code as part of the problem) it is possible for very large islands to appear. In `gausfit.py`, what happens with these in detail is that `fit_island_iteratively` gets called, it fails and calls `fit_island` in 'default' mode, `inigaus_fbdsm` is called and gives a very large list of Gaussians (over 400 for my test case) and then when `fit_iter` is run it passes all those Gaussians to the LM minimization routine which never returns.

I think it's obviously nuts in this case to try to fit with all the free parameters of the hundreds of Gaussians -- LM can't do this even if we wanted it to -- and my 'fix' is to check if the list of Gaussians provided by `inigaus_fbdsm` is longer than some number (I have used 25) and to fall back on 'simple' fitting if so. If someone would like to comment on this strategy I can make a PR.

**Comment by darafferty** [comment]
This approach sound reasonable to me, since, as you say, it's silly to try to fit such emission in the standard way. Please do make a PR, and I'll test the changes and merge them.
