### ISSUE TITLE
AttributeError: 'Extension' object has no attribute 'extra_cxx_compile_args'

### ISSUE THREAD

**Issue by MichelleLochner** [lofar-astron/PyBDSF#168]
Just in case anyone has the same problem as me (or perhaps there's a better way of solving it), I got this error buried in amongst a very large traceback:

`AttributeError: 'Extension' object has no attribute 'extra_cxx_compile_args'`

I noticed that there were some very similar attributes that were initialised to empty lists in the `setup.py` file so I adjusted the for loop: 

```
for ext in extensions:
    ext.extra_f77_compile_args = []
    ext.extra_f90_compile_args = []
    ext.extra_c_compile_args = []
    ext.extra_cxx_compile_args = []
```

And everything seems to have installed ok and is running. 

I'm using Ubuntu 21.10, python 3.9 and virtualenv.

**Comment by gmloose** [comment]
Thanks for reporting. This is a known issue, and I'm currently working on it. The fix for this issue is to add `Extension` to `from numpy.distutils.core import ...` in line 7.
