### ISSUE TITLE
Import bdsf issue

### ISSUE THREAD

**Issue by agwilber** [lofar-astron/PyBDSF#170]
Hi all,

I installed pybdsf on my Mac, with the advice from some past issues, and all seemed to go well with the compiler. However, now when I try to import bdsf I get this error:

```
>>> import bdsf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aw2025/pybdsf_install/PyBDSF/bdsf/__init__.py", line 21, in <module>
    from .collapse import Op_collapse
  File "/Users/aw2025/pybdsf_install/PyBDSF/bdsf/collapse.py", line 11, in <module>
    from . import _cbdsm
ImportError: cannot import name '_cbdsm' from partially initialized module 'bdsf' (most likely due to a circular import) (/Users/aw2025/pybdsf_install/PyBDSF/bdsf/__init__.py)
```

Has anyone else seen this?
Thank you!

**Comment by gmloose** [comment]
No, can you give a bit more detail?
One thing that springs to mind. Are you running your Python shell from the source directory? If so, Python might get confused. I've been bitten by that a couple of times, but never took the time to figure out what exactly is going wrong. In my case it helped to run Python from any other directory _outside_ the source tree.

**Comment by agwilber** [comment]
Yes I was inside the source directory cloned from GitHub -- so that could explain the circular import! If I go outside that source directory the module 'bdsf' is not found at all with python. I suppose this was because I hadn't put the location of the PyBDSF directory in my path, but when I do that I still get the error that the module is not found. I suppose I don't know where the script pybdsf gets install on my Mac because it's not in /usr/local/bin or /usr/bin...

**Comment by agwilber** [comment]
> No, can you give a bit more detail?
> One thing that springs to mind. Are you running your Python shell from the source directory? If so, Python might get confused. I've been bitten by that a couple of times, but never took the time to figure out what exactly is going wrong. In my case it helped to run Python from any other directory _outside_ the source tree.

**Comment by agwilber** [comment]
> Yes I was inside the source directory cloned from GitHub -- so that could explain the circular import! If I go outside that source directory the module 'bdsf' is not found at all with python. I suppose this was because I hadn't put the location of the PyBDSF directory in my path, but when I do that I still get the error that the module is not found. I suppose I don't know where the script pybdsf gets installed on my Mac because it's not in /usr/local/bin or /usr/bin...

It's not in the anaconda bin so perhaps it did not successfully install. I used the clang++ method as described [here:](https://github.com/lofar-astron/PyBDSF/issues/104#issuecomment-509267088 )

**Comment by gmloose** [comment]
Did you actually _install_ `bdsf`? E.g. by running `pip install .`, where `.` is the current directory, which must be the top-level source directory. It is also recommended to create a `virtualenv`, unless you're using `conda`.

**Comment by agwilber** [comment]
Hi again, I am using conda and thought the installation was successful after editing the boost libraries in setup.py (boost py38), but I see that the installation was not successful (pip install . ) ... Unfortunately it is really hard to find the source of the error in the traceback.... I will close this issue because obviously the import failed since there wasn't a completed installation. Thank you for your help!

**Comment by gmloose** [comment]
I see you're using python 3.8. There is a known issue with the current `setup.py` for Python >= 3.8. [Here](https://github.com/lofar-astron/PyBDSF/issues/167#issuecomment-1017526591) is a quick fix. A permanent solution will be committed soon.

**Comment by mhardcastle** [comment]
Any update on that permanent solution?

**Comment by gmloose** [comment]
The problem should have been solved now. Did you try the latest release that we published three months ago?

**Comment by mhardcastle** [comment]
I was asking for a friend, but yes that works now in 3.8, thanks!
