### ISSUE TITLE
Incompatibility with scipy 1.8.0

### ISSUE THREAD

**Issue by gabicca** [lofar-astron/PyBDSF#171]
Using PyBDSF with the newest version of scipy (1.8.0) causes an import error:

```
Traceback:
....
    import bdsf
/usr/local/lib/python3.9/site-packages/bdsf/__init__.py:33: in <module>
    from .wavelet_atrous import Op_wavelet_atrous
/usr/local/lib/python3.9/site-packages/bdsf/wavelet_atrous.py:22: in <module>
    from scipy.signal.signaltools import _centered
E   ImportError: cannot import name '_centered' from 'scipy.signal.signaltools' (/usr/local/lib/python3.9/site-packages/scipy/signal/signaltools.py)
```
Could this be fixed please? Thanks!

**Comment by ludwigschwardt** [comment]
FWIW, Scipy [warned](https://docs.scipy.org/doc/scipy-1.8.0/html-scipyorg/reference/#importing-from-scipy) about this (not that I haven't done the same in the past!) :-)

This does not seem too onerous to replace. The missing function is small enough:
```python
def _centered(arr, newshape):
    # Return the center newshape portion of the array.
    newshape = np.asarray(newshape)
    currshape = np.array(arr.shape)
    startind = (currshape - newshape) // 2
    endind = startind + newshape
    myslice = [slice(startind[k], endind[k]) for k in range(len(endind))]
    return arr[tuple(myslice)]
```

**Comment by darafferty** [comment]
Thanks for reporting this issue and providing the code for the function! That made it very easy to fix, and I've made a PR for it (#172) that should be merged shortly.

**Comment by gabicca** [comment]
> Thanks for reporting this issue and providing the code for the function! That made it very easy to fix, and I've made a PR for it (#172) that should be merged shortly.

Hi @darafferty , Thanks for taking quick actions and fixing this problem!

Out of interest, how often do you release new wheels of PyBDSF? We are using PyPi to install the package from, not the git repository, which means if the latest wheel doesn't contain the change we won't have it. We used to install from git, but that started to cause problems, and since the new python3.9 wheel was released we got back to using that (which works well).

**Comment by gmloose** [comment]
We usually release new wheels when there's a new release. However, since it's been quite a while since the latest official release (1.9.2), binary wheels for Python 3.7 and 3.8 were uploaded later.

We will soon release 1.10.0, which will contain binary wheels for Python 3.6, 3.7, 3.8 and 3.9.

I'm closing this issue now. Feel free to reopen it if necessary.

**Comment by gabicca** [comment]
> We usually release new wheels when there's a new release. However, since it's been quite a while since the latest official release (1.9.2), binary wheels for Python 3.7 and 3.8 were uploaded later.
> 
> We will soon release 1.10.0, which will contain binary wheels for Python 3.6, 3.7, 3.8 and 3.9.
> 
> I'm closing this issue now. Feel free to reopen it if necessary.

Thank you! I'm looking forward to the new release.
