### ISSUE TITLE
infinite looping in rms map code with some options

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/PyBDSF#18]
In rmsimage.py -- calculate_maps it is possible to get stuck in an infinite loop if rms_box is set, adaptive_rms_box is True, rms_box_bright is set, and spline_rank=1. In this case, if N.any(rms < 0.0) after the map_2d call, nothing will change -- we fall through to the code where it checks for opts.spline_rank > 1, but since it isn't, we just endlessly loop round the while loop doing the same map_2d call again and again.

I have pushed to my fork a 'fix' which raises a runtime error if this happens, but I wonder if the logic needs a more careful look?

**Comment by darafferty** [comment]
I think raising the error is fine, but I wonder where the negative rms values are coming from -- could they be due to the interpolation, even though spline_rank=1?

**Comment by mhardcastle** [comment]
I think that's possible, but didn't dig deep enough to find out why in my brief look at the problem. I do have a test case that triggers it...

**Comment by mhardcastle** [comment]
My 'fix' here didn't work in the case where the code degrades the spline_rank to 1 itself, so I've fixed the fix and will make a PR shortly. (And, not coincidentally, now have another test case that gives negative rms when spline_rank=1. This is in the a trous part of the code, so the rms map is determined from the residual map I think, which may be part of the issue.)
