### ISSUE TITLE
Numpy alen issue

### ISSUE THREAD

**Issue by epolisensky** [lofar-astron/PyBDSF#182]
Running PyBDSF 1.10.1 and numpy 1.23.3 I get this warning and error:

--> Calculating background rms and mean images
/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
...
File "/home/vpipe/.local/lib/python3.8/site-packages/bdsf/rmsimage.py", line 859, in fill_masked_regions
    num_unmasked = N.alen(goodcutout)
...
AttributeError: module 'numpy' has no attribute 'alen'

Replacing N.alen() with len() seems to fix it

**Comment by tammojan** [comment]
This was fixed a week ago in #180. Could you upgrade to the latest master version?
