### ISSUE TITLE
Installation MacOS

### ISSUE THREAD

**Issue by patoch01220** [lofar-astron/PyBDSF#183]
Hello, 
I need to install pyBDSF for a project but It has been few days that I am struggling to install it (I am working with Karabo which uses PyBDSF).

I've tried the 3 ways on installing it but still didn't work. Here is the traceback after running the comamnd `pip3 install bdsf`:

```
clang++ -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g build/temp.macosx-10.9-universal2-cpython-310/src/c++/Fitter_dn2g.o build/temp.macosx-10.9-universal2-cpython-310/src/c++/Fitter_dnsg.o build/temp.macosx-10.9-universal2-cpython-310/src/c++/Fitter_lmder.o build/temp.macosx-10.9-universal2-cpython-310/src/c++/MGFunction1.o build/temp.macosx-10.9-universal2-cpython-310/src/c++/MGFunction2.o build/temp.macosx-10.9-universal2-cpython-310/src/c++/cbdsm_main.o build/temp.macosx-10.9-universal2-cpython-310/src/c++/stat.o build/temp.macosx-10.9-universal2-cpython-310/src/c++/num_util/num_util.o -L/private/var/folders/zy/jdlqrb6s6_v9qmkh7j15y6w40000gn/T/pip-install-yvhea7h4/bdsf_7b29be0c1b364d1d9f0924abc4be4f8d/src/minpack -L/private/var/folders/zy/jdlqrb6s6_v9qmkh7j15y6w40000gn/T/pip-install-yvhea7h4/bdsf_7b29be0c1b364d1d9f0924abc4be4f8d/src/port3 -L/usr/local/lib -L/usr/local/lib -lminpack -lport3 -lgfortran -lboost_python310-mt -lboost_numpy310-mt -o build/lib.macosx-10.9-universal2-cpython-310/bdsf/_cbdsm.cpython-310-darwin.so
      ld: library not found for -lgfortran
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      error: Command "clang++ -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g build/temp.macosx-10.9-universal2-cpython-310/src/c++/Fitter_dn2g.o build/temp.macosx-10.9-universal2-cpython-310/src/c++/Fitter_dnsg.o build/temp.macosx-10.9-universal2-cpython-310/src/c++/Fitter_lmder.o build/temp.macosx-10.9-universal2-cpython-310/src/c++/MGFunction1.o build/temp.macosx-10.9-universal2-cpython-310/src/c++/MGFunction2.o build/temp.macosx-10.9-universal2-cpython-310/src/c++/cbdsm_main.o build/temp.macosx-10.9-universal2-cpython-310/src/c++/stat.o build/temp.macosx-10.9-universal2-cpython-310/src/c++/num_util/num_util.o -L/private/var/folders/zy/jdlqrb6s6_v9qmkh7j15y6w40000gn/T/pip-install-yvhea7h4/bdsf_7b29be0c1b364d1d9f0924abc4be4f8d/src/minpack -L/private/var/folders/zy/jdlqrb6s6_v9qmkh7j15y6w40000gn/T/pip-install-yvhea7h4/bdsf_7b29be0c1b364d1d9f0924abc4be4f8d/src/port3 -L/usr/local/lib -L/usr/local/lib -lminpack -lport3 -lgfortran -lboost_python310-mt -lboost_numpy310-mt -o build/lib.macosx-10.9-universal2-cpython-310/bdsf/_cbdsm.cpython-310-darwin.so" failed with exit status 1
      
      ########### EXT COMPILER OPTIMIZATION ###########
      Platform      :
        Architecture: unsupported
        Compiler    : clang
      
      CPU baseline  :
        Requested   : optimization disabled
        Enabled     : none
        Flags       : none
        Extra checks: none
        Requested   : optimization disabled
      
      CPU dispatch  :
        Enabled     : none
        Generated   : none
      CCompilerOpt.cache_flush[809] : write cache to path -> /private/var/folders/zy/jdlqrb6s6_v9qmkh7j15y6w40000gn/T/pip-install-yvhea7h4/bdsf_7b29be0c1b364d1d9f0924abc4be4f8d/build/temp.macosx-10.9-universal2-cpython-310/ccompiler_opt_cache_ext.py
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bdsf
Failed to build bdsf
ERROR: Could not build wheels for bdsf, which is required to install pyproject.toml-based projects
```

Anyways, I do have a folder bdsf in my conda environment, that's why I also tried using Karabo like this and at some point I have the issue 
```
ModuleNotFoundError: No module named 'bdsf._cbdsm'
```

I have read some issues about similar problems, but never found a way to resolve it. 
Do you have any idea ?

Thank you very much!

**Comment by tammojan** [comment]
The command you're posting now indicates that you do not have a fortran compiler on your system. Unfortunately that is required to get pybdsf going.
What system are you on? Mac or Linux?

**Comment by patoch01220** [comment]
> The command you're posting now indicates that you do not have a fortran compiler on your system. Unfortunately that is required to get pybdsf going. What system are you on? Mac or Linux?

Yes I say this error message. 
Firstly I am on Mac and I think I did installed it because when I run the command `sudo find /usr -iname 'libgfortran*.a' | xargs shasum`I get those results:
```
1ddf80de523937442a622452730d3950476fa90e  /usr/local/Cellar/gcc/12.2.0/lib/gcc/current/libgfortran.a
1ddf80de523937442a622452730d3950476fa90e  /usr/local/Cellar/gcc/12.2.0/lib/gcc/12/libgfortran.a
```

But yeah I also investigate this but unfortunately I didn't find much things to do.

**Comment by tammojan** [comment]
Maybe you can help python find this file (or rather `libgfortran.dylib` which is probably in the same directory) by running
```
`DYLD_LIBRARY_PATH=/usr/local/Cellar/gcc/12.2.0/lib/gcc/12/:$DYLD_LIBRARY_PATH pip3 install pybdsf
```
Sorry you have to jump through these hoops, pybdsf is really showing its age.

**Comment by tammojan** [comment]
The conda env should not be the issue; though it might also help to install `gfortran` inside that fortran environment. But I would try to go with the homebrew gfortran first.

Is the error you get still the same? With the `DYLD_LIBRARY_PATH`, `clang++` is instructed to find libraries also in the path `/usr/local/Cellar/gcc/12.2.0/lib/gcc/12/`, so for linking `-lgfortran` it should look for a `libgfortran.dylib` for each of the directories in `$DYLD_LIBRARY_PATH`.

**Comment by tammojan** [comment]
> When you say install it in my conda env, i just need to run the command `brew install gcc` once i have activated the env right? (I'm new to conda)

No, to install something in conda, you have to type ` conda install -c conda-forge gfortran`. But I wonder why the `DYLD_LIBRARY_PATH` hack didn't work...

**Comment by patoch01220** [comment]
Okay, so new update, I did install gfortran on the conda env and now, by running again the last command to install PyBDSF, i have this error:
```
x86_64-apple-darwin13.4.0-clang: build/src.macosx-10.9-universal2-3.10/bdsf/_pytesselatemodule.c
      x86_64-apple-darwin13.4.0-clang: build/src.macosx-10.9-universal2-3.10/build/src.macosx-10.9-universal2-3.10/bdsf/fortranobject.c
      clang-12: error: the clang compiler does not support '-march=core2'
      clang-12: error: the clang compiler does not support '-march=core2'
      error: Command "x86_64-apple-darwin13.4.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/patoch/opt/anaconda3/envs/karabo_dev_env/include -D_FORTIFY_SOURCE=2 -isystem /Users/patoch/opt/anaconda3/envs/karabo_dev_env/include -Ibuild/src.macosx-10.9-universal2-3.10/build/src.macosx-10.9-universal2-3.10/bdsf -I/private/var/folders/zy/jdlqrb6s6_v9qmkh7j15y6w40000gn/T/pip-build-env-8hxb10ha/overlay/lib/python3.10/site-packages/numpy/core/include -Ibuild/src.macosx-10.9-universal2-3.10/numpy/distutils/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c build/src.macosx-10.9-universal2-3.10/build/src.macosx-10.9-universal2-3.10/bdsf/fortranobject.c -o build/temp.macosx-10.9-universal2-cpython-310/build/src.macosx-10.9-universal2-3.10/build/src.macosx-10.9-universal2-3.10/bdsf/fortranobject.o -MMD -MF build/temp.macosx-10.9-universal2-cpython-310/build/src.macosx-10.9-universal2-3.10/build/src.macosx-10.9-universal2-3.10/bdsf/fortranobject.o.d" failed with exit status 1
      
      ########### EXT COMPILER OPTIMIZATION ###########
      Platform      :
        Architecture: unsupported
        Compiler    : clang
      
      CPU baseline  :
        Requested   : optimization disabled
        Enabled     : none
        Flags       : none
        Extra checks: none
        Requested   : optimization disabled
      
      CPU dispatch  :
        Enabled     : none
        Generated   : none
      CCompilerOpt.cache_flush[809] : write cache to path -> /private/var/folders/zy/jdlqrb6s6_v9qmkh7j15y6w40000gn/T/pip-install-7lfyru0b/bdsf_c22ed17d339d4f5e9e27ac991907ca14/build/temp.macosx-10.9-universal2-cpython-310/ccompiler_opt_cache_ext.py
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bdsf
Failed to build bdsf
ERROR: Could not build wheels for bdsf, which is required to install pyproject.toml-based projects
```

**Comment by gmloose** [comment]
What kind of CPU architecture are you on? Is this M1?

**Comment by patoch01220** [comment]
No i am on an Intel I7 

> What kind of CPU architecture are you on? Is this M1?

**Comment by patoch01220** [comment]
What is also weird, is that when I run the command `clang --print-supported-cpus ` I do have the "core2" present, even though I don't have the "native" one.

**Comment by gmloose** [comment]
Is there a difference in compiler versions between the system-wide one and the one inside the Conda environment? That might explain the difference in behavior.

It's a bit strange that `-march=native` throws an error. Clang should be able to determine the CPU type of the host system. Have you tried using GCC instead?

**Comment by darafferty** [comment]
There is an issue [here](https://github.com/Yale-LILY/SummerTime/issues/116) that mentions the `-march=native` error with clang. Not sure if it's the same problem you're having, though.

**Comment by patoch01220** [comment]
> Is there a difference in compiler versions between the system-wide one and the one inside the Conda environment? That might explain the difference in behavior.
> 
> It's a bit strange that `-march=native` throws an error. Clang should be able to determine the CPU type of the host system. Have you tried using GCC instead?

The gcc version is the same but the python3 one is different (I have both python 3.9.12 and 3.10.7 installed on my computer).

What do cou mean by `Have you tried using GCC instead?` ?

**Comment by patoch01220** [comment]
I've trie

> There is an issue [here](https://github.com/Yale-LILY/SummerTime/issues/116) that mentions the `-march=native` error with clang. Not sure if it's the same problem you're having, though.

I've tried it but didn't work as well

**Comment by patoch01220** [comment]
Anyways, I just tried creating a new conda env to see if it was the environment I had that was the issue. 
So I've created a new conda env, activate the env and then ran the command pip3 install bdsf which succeed well. 
So I think my previous conda environement had an issue and might just remove it and use the new one then. 

Anyways I have another question regarding bdsf.
Let's first call my first conda env (the one that can't install bdsf) as the "conda env 1" et the "conda env 2" would be the new one I've just created. 

I compared the files in each conda env and on the base env, to see the difference with the bdsf. I then saw that in the first conda env, I had a folder bdsf (Which I don't how he got there as the installation failed multiple times) but the only difference is that the files: "_pytesselate.cpython-39-darwin.so" and "_cbdsm.cpython-39-darwin.so" are missing. 

Why I am telling you this? As I told you, I was working on my project which uses the tool Karabo. This tool uses your Pybdsf and when calling for the source detection function, I had the error `No module named 'bdsf._cbdsm'`. Then by going deeper and analysing the packade bsdf in the first conda env, I fought it was quite logic because there wasn't any _cbdsm file or anything present. That's why the lines `from . import _cbdsm` in your code didn't work and that's also why I thought the installation of pyBDSF failed. At this point I tried reinstalling it and then as I saw it wasn't working, I did create this issue. 

But now I see that in the new conda env (so the one that succeed installing bsdf), there is this file named: "_cbdsm.cpython-39-darwin.so" in the package "bdsf". So I've tried running my code on this new environment, but unfortunately I still have this error  `No module named 'bdsf._cbdsm'`.

Do you have any ideas about this error ?

**Comment by patoch01220** [comment]
Okay I resolved all my issues:

- For the installation, I created a fresh new conda env under python 3.9.13 and it worked well. I also tried under python 3.10 and 3.8, but it didn't work for me). Anyways, i'll use the python 3.9
- Concerning the import of `_cbdsm`, The issue was clearly due to the fact that I was missing at first and then by installing bdsf correctly, I had it. Then the errro `ImportError: dlopen(/Users/patoch/opt/anaconda3/envs/test_env/lib/python3.9/site-packages/bdsf/_cbdsm.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (__ZN5boost6python15instance_holder8allocateEP7_objectmmm)`showed up and I did succeed resolving it by unistalling bdsf like so: `pip3 unistall bdsf` and reinstalling it using this line: `pip3 install --no-cache-dir bdsf` and now it seems to work well.

- Also note that you can encounter an error about numpy not having a `alen()` function. This happens because in the files `collapse.py` and `rmsimage.py` there was still some calls of `np.alen()`. I think that installing PyBBDSF with pip3 doesn't gives us the last version of BDSF, and so to resolve this, just copy paste the original files of the github into your files in the folder bdsf and it should resolve it. 

Let me know if you need more informations and thanks everyone for your very helpful help ! :)

**Comment by gmloose** [comment]
Given the fact that @patoch01220 resolved all his issues, I think we can safely close this ticket. Feel free to reopen it, if you think otherwise.
