### ISSUE TITLE
The online documentation has disappeared

### ISSUE THREAD

**Issue by jt2553** [lofar-astron/PyBDSF#184]
Your documentation no longer appears to be hosted at the link http://www.astron.nl/citt/pybdsf. 'Page not found' is returned

**Comment by tammojan** [comment]
Thanks. We noticed, and are planning to pick it up, probably on a Friday afternoon.

**Comment by tammojan** [comment]
We moved the documentation to readthedocs: https://pybdsf.readthedocs.io
