### ISSUE TITLE
manylinux2010 deprecation

### ISSUE THREAD

**Issue by juliancarrivick** [lofar-astron/PyBDSF#187]
According to [docs](https://github.com/pypa/manylinux#manylinux2010-centos-6-based---eol), `manylinux2010` was EOL on Aug 1st.

Potential [updated alternatives](https://github.com/pypa/manylinux#docker-images) include `manylinux2014` (CentOS 7) and `manylinux_2_28` (Almalinux 8 - CentOS replacement) and the existing docker builds succeed with both. 

I'm happy to do some work to update everything, but there's a few things which would need to be decided:
- `manylinux2014` or `manylinux_2_28`? I would be inclined to go with `2_28` as it is more recent
- Do we remove the existing `manylinux2010` builds? It may be safer to keep them in parallel for some period of time
- Is there some way - ideally in CI - to verify there is no regressions across versions?

**Comment by gmloose** [comment]
We are aware of this. I was planning to move to `manylinux2014` with the next release. However, there's no date set, yet, for this.
