### ISSUE TITLE
PyBDSF gaussian fitting details

### ISSUE THREAD

**Issue by Kincaidr** [lofar-astron/PyBDSF#225]
Hello,

I have a simple question relating to the gaussian fitting procedure of PyBDSF. I am currently doing a radio simulation to derive source count corrections and for sanity check need to make sure my injected source properties (such as source size, peak flux, etc) match that with recovered. I ma using PyBDSF to extract the recovered sources properties.

The issue is that there is alot of scatter when comparing injected vs recovered particularly for major axis and total flux. When I locate these sources with large differences and do manual gaussian fitting with CASA viewer then the properties do match to my injected.

Si it seems the gaussian fitting PyBDSF is doing is not the same as with CASA. Do you know what it does different so that I can implement it into my simulation?

Thanks.

**Comment by JonahDW** [comment]
Sorry to tag onto this, I don't have the answer, but I would be interested in knowing this as well. I have done simulations in which the recovered total flux of sources by PyBDSF was systematically higher than the input flux, especially for low S/N sources. @Kincaidr do you see anything like that, or do you just see more scatter in your results?

**Comment by Kincaidr** [comment]
@JonahDW I managed to solve this problem now. My problem was the source size interpretation. PyBDSF returns the FWHM of the major and minor axis. In my simulation I assign a intrisnic size which si realted to the FWHM:` fwhm_x = np.sqrt(int_size**2 + BMAJ**2)
`

**Comment by Kincaidr** [comment]
If i plot the recovered properties from PyBDSF when injected on a low noise gaussian image with that of injected properties I get a 1:1 fit:

![image](https://github.com/user-attachments/assets/c6741257-6a41-407f-a1e9-0d8881e0dd41)
