### ISSUE TITLE
The scripting interface does not respect "outdir" as a parameter

### ISSUE THREAD

**Issue by zack466** [lofar-astron/PyBDSF#232]
Minimum example:

```python
import bdsf

# assume IMAGE_PATH is not located in OUTPUT_DIR
bdsf.process_image(IMAGE_PATH, outdir=OUTPUT_DIR)

# The output files will be placed in the base directory of IMAGE_PATH instead of OUTPUT_DIR as expected.
```
From what I can tell, the reason is that the following happens:
1. `bdsf.process_image()` defines `img = Image({'filename': input})` since IMAGE_PATH is not a parameter save file, and then calls `img.process(**kwargs)`, which calls `interface.process(img, **kwargs)`.
2. However, the interface `process` function calls `set_up_output_paths(img.opts)`, ignoring the `outdir` key in `**kwargs`. And since `img` only contains `filename` in its `opts` dictionary, `set_up_output_paths(img.opts)` is not aware of the `outdir` parameter and therefore returns the base directory of `IMAGE_PATH` instead of `outdir`.
3. As a result, the incorrect base directory is returned. This is also a problem since if `IMAGE_PATH` is located in a read-only directory, then the program will fail as it cannot write files to that directory. It should be possible to pass in a different `outdir` with write-access to avoid this.

**Comment by tmartinezML** [comment]
I was just about to write the same issue since I'm having the exact same problem and came to the same conclusion, so thanks @zack466.
A fix for this would be awesome.
