### ISSUE TITLE
Python 3.13 build failure

### ISSUE THREAD

**Issue by olebole** [lofar-astron/PyBDSF#246]
On Debian, we are currently introducing Python 3.13 into our standard Python package builds. For pybdsf, there is however a compilation problem with Python 3.13 that I do not really understand: The compilation fails with
```
CMake Error at cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "/build/pybdsf-1.11.1/_skbuild/linux-x86_64-3.13/cmake-build/_pytesselate.cpython-313-x86_64-linux-gnu.so":
  No such file or directory.
```
but I couldn't find the built attempt of that shared library. Full log [here](https://salsa.debian.org/debian-astro-team/pybdsf/-/jobs/6612895).
Any ideas what the problem could be?

This was also reported as [Debian#1081693](https://bugs.debian.org/1081693) in our bug tracking system.

**Comment by tammojan** [comment]
Looks related to the many errors like [this one](https://salsa.debian.org/debian-astro-team/pybdsf/-/jobs/6612895#L2586):
```
param_eval: got "eval() arg 1 must be a string, bytes or code object" on 4
```
Could it be that this causes `_pytesselate.cpython` to not build, which in turn cannot be installed?

**Comment by olebole** [comment]
Could be, but I don't understand this.

**Comment by gmloose** [comment]
Curious. I just tried to build PyBDSF for Python 3.13 using `cibuildwheel` and it "just works." 
One thing to check: are you using `numpy<2`? There are issues with NumPy 2.x, that haven't been resolved, AFAIK.

**Comment by gmloose** [comment]
The Debian bug you refer to is for an `aarch64` build. Is that the only architecture that's failing?

**Comment by olebole** [comment]
The build is with numpy 1.26.4. And the failure happens on x86_64 as well, see the build log linked above.

What I could imagine: at build time, we have both Python 3.12 and 3.13 installed, with the default Python (still) being 3.12. The full build command is (from the log, manually word-wrapped)
```
/usr/bin/cmake /build/pybdsf-1.11.1 -G Ninja --no-warn-unused-cli \
 -DCMAKE_INSTALL_PREFIX:PATH=/build/pybdsf-1.11.1/_skbuild/linux-x86_64-3.13/cmake-install \
 -DPYTHON_VERSION_STRING:STRING=3.13.0 -DSKBUILD:INTERNAL=TRUE \
 -DCMAKE_MODULE_PATH:PATH=/usr/lib/python3/dist-packages/skbuild/resources/cmake \
 -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3.13 \
 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.13 \
 -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.13.so \
 -DPython_EXECUTABLE:PATH=/usr/bin/python3.13 \
 -DPython_ROOT_DIR:PATH=/usr -DPython_FIND_REGISTRY:STRING=NEVER \
 -DPython_INCLUDE_DIR:PATH=/usr/include/python3.13 \
 -DPython_NumPy_INCLUDE_DIRS:PATH=/usr/lib/python3/dist-packages/numpy/core/include \
 -DPython3_EXECUTABLE:PATH=/usr/bin/python3.13 \
 -DPython3_ROOT_DIR:PATH=/usr -DPython3_FIND_REGISTRY:STRING=NEVER \
 -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.13 \
 -DPython3_NumPy_INCLUDE_DIRS:PATH=/usr/lib/python3/dist-packages/numpy/core/include \
 -DCMAKE_BUILD_TYPE:STRING=Release
```
which looks reasonable to me. And the shared libraries `natgridmodule.cpython-313-x86_64-linux-gnu.so` and `_cbdsm.cpython-313-x86_64-linux-gnu.so` are built (linked) properly. **But** in the compilation of pytesselate, it says
```
[2/7] Compiling Fortran object _pytesselate.cpython-312-x86_64-linux-gnu.so.p/_pytesselate-f2pywrappers.f.o
[3/7] Compiling Fortran object _pytesselate.cpython-312-x86_64-linux-gnu.so.p/pytess_simple.f.o
[4/7] Compiling Fortran object _pytesselate.cpython-312-x86_64-linux-gnu.so.p/pytess_roundness.f.o
[…]
[7/7] Linking target _pytesselate.cpython-312-x86_64-linux-gnu.so
[…]
[138/139] Linking CXX shared module _cbdsm.cpython-313-x86_64-linux-gnu.so
[138/139] Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "/build/pybdsf-1.11.1/_skbuild/linux-x86_64-3.13/cmake-build/_pytesselate.cpython-313-x86_64-linux-gnu.so":
  No such file or directory.
```
This looks to me that for some reason the pytesselate build does not use the Python version taken from the Ninja defines, but the standard Python (which is 3.12)?

**Comment by olebole** [comment]
Just found the configuration output at the beginning of the pytesselate build:
```
The Meson build system
Version: 1.6.0
Source dir: /tmp/tmp1sbt3s_z
Build dir: /tmp/tmp1sbt3s_z/bbdir
Build type: native build
Project name: _pytesselate
Project version: 0.1
Fortran compiler for the host machine: gfortran (gcc 14.2.0 "GNU Fortran (Debian 14.2.0-8) 14.2.0")
Fortran linker for the host machine: gfortran ld.bfd 2.43.1
C compiler for the host machine: cc (gcc 14.2.0 "cc (Debian 14.2.0-8) 14.2.0")
C linker for the host machine: cc ld.bfd 2.43.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program /usr/bin/python3 found: YES (/usr/bin/python3)
Did not find pkg-config by name 'pkg-config'
Found pkg-config: NO
Run-time dependency python found: YES 3.12
Library quadmath found: YES
Build targets in project: 1
```
This really looks that there is another check for Python, where it takes the default one (which is the wrong one in our case).

**Comment by gmloose** [comment]
Looking at the command-line, it looks like it's using the default (Python 3.12) NumPy. That will probably wreak havoc when trying to build binaries for Python 3.13. I think you need to coerce CMake to use NumPy for the target Python version (3.13).

**Comment by gmloose** [comment]
I'm not sure how the Docker images for Python solve this issue. These are used by `cibuildwheel` to build binary wheels. And I can successfully build PyBDSF for Python 3.13 with `cibuildwheel`.

**Comment by olebole** [comment]
Numpy is here compiled for both Python versions, i.e. it has modules for Python 3.12 and 3.13.

**Comment by gmloose** [comment]
Yeah, so maybe that's the culprit. What if you add `-DF2PY_EXECUTABLE=/usr/bin/f2py3.13` to the CMake command-line.

**Comment by olebole** [comment]
The problem is that we want to build it for both, and so it is first build with
```
python3.13 -m build --skip-dependency-check --no-isolation --wheel --outdir /build/pybdsf-1.11.1/.pybuild/cpython3_3.13
```
and then again with python3.12. I don't see a room to specify a specific f2py here.

**Comment by gmloose** [comment]
What about:
```
CMAKE_ARGS="-DF2PY_EXECUTABLE=/usr/bin/f2py3.13" python3.13 -m build --skip-dependency-check --no-isolation --wheel --outdir /build/pybdsf-1.11.1/.pybuild/cpython3_3.13
```

**Comment by olebole** [comment]
What finally solved it for me was to add and additional line
```
set(F2PY_EXECUTABLE "${PYTHON_EXECUTABLE}" "-m" "numpy.f2py")
```
in the `CMakefile.txt`. With this, it builds fine for both Python 3.12 and 3.13.

Thank you for your help here. I am closing this because I think it is rather Debian-related. IMO in Debian the `find_package(F2PY)` should be extended here to allow this case; I started a discussion in our mailing list about this.
