### ISSUE TITLE
very large RA and DEC errors

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/PyBDSF#31]
Hey,

I am running pybdsf with:

bdsf.process_image('pybdsf_error_high.fits', thresh_isl=4.0, thresh_pix=5.0, rms_box=(160,50), rms_map=True, mean_map='zero', ini_method='intensity', adaptive_rms_box=True, adaptive_thresh=150, rms_box_bright=(60,15), group_by_isl=False, group_tol=10.0,output_opts=True, output_all=True, atrous_do=True,atrous_jmax=4, flagging_opts=True, flag_maxsize_fwhm=0.5,advanced_opts=True, blank_limit=None,frequency=1.5E6)

Looking at the gaussian components catalogue its seems everything is normal. However, the source catalogue contains a source with reasonable peak flux, total flux and position, but rather excessive RA and DEC errors of ~5E6 which I would have thought cant be correct.

The image is a bit too big to post here but I can email over a link (I tried making a smaller cutout but in the cutout pybdsf returned normal source position errors).

Thanks,

Tim

**Comment by twshimwell** [comment]
Seems to be related to the image size. If I make cutouts I don't see the error until the cutouts get very large (the untrimmed image I am running it on has a size of 9404x9404 so its quite big)

**Comment by darafferty** [comment]
Strange -- I can't see why the errors would be related to the input image size. Can you email the image to me? I will try to debug it.

**Comment by twshimwell** [comment]
Thanks. I've emailed it over.

**Comment by darafferty** [comment]
Tim, I think I've fixed the issue. Can you update and try it again?

**Comment by twshimwell** [comment]
Excellent. Thanks very much David it seems to be fixed. :)
