### ISSUE TITLE
Precision on catalogue output

### ISSUE THREAD

**Issue by IanHeywood** [lofar-astron/PyBDSF#33]
I'm running PyBDSF on a map that's deep enough such that I'm hitting the precision limit on the source fluxes, and the catalogue output is 'quantised' into bins.

My cheap fix to get around this was to multiply the image pixels by 1000 and then divide this out in the catalogue, however when I do this I get a lot of spurious sources (about 3-4 times as many components in total as in the original map). The only thing I can think of is that the new pixels values are affecting the confusion calculation, and thus the local thresholding. I adjusted the BUNIT keyword to 'mJy/beam' but I'm not sure if PyBDSF makes use of this. (A search for BUNIT in the repository has no results.)

I can probably get around it by specifying the box size, but it might be worth adjusting the numerical precision of the catalogue output to cope with very deep images.

Thanks.

**Comment by darafferty** [comment]
Are you writing the catalogs out in FITS format (the default for the `write_catalog` task)? If so, it should have the full double-precision values.

**Comment by IanHeywood** [comment]
I'm using ASCII .gaul format.
