### ISSUE TITLE
Provide external noise map

### ISSUE THREAD

**Issue by cyriltasse** [lofar-astron/PyBDSF#38]
Is there a way to provide a noise map/mean image to pybdsf while doing process_image? That step It's just super slow, and I have to reapeat something in an image (inject sources - extract) , and my noise map is always the same...

**Comment by cyriltasse** [comment]
That's probably a no? :) I looked a bit at the code and it seems not too difficult to add the option...

**Comment by cyriltasse** [comment]
I've made changes here:

https://github.com/cyriltasse/PyBDSF/commit/6652288e5c3d9e1c4d2511b32f460be28e426e15

Not sure it's the right was to do - I see you're using `read_image_from_file` that takes a filename, and image object and a dirin name. It was simpler to use just pyfits, since no object was being returned above - just 2D numpy arrays. Simple hack that should work.

**Comment by tammojan** [comment]
An advantage of `read_image_from_file` is also that it could use casa images. Other minor thing is that the import of pyfits can elsewhere in PyBDSF also take `astropy.fits as pyfits` to use the astropy version of pyfits. For consistency you could add this.

Other than these minor things, the change looks good to me. Could you make a pull request? Then @darafferty can have a look at it and merge it.

**Comment by cyriltasse** [comment]
Yeah I saw that too (and I'm not sure yet of I should like flip the array or so - did not test yet) - I just didn't know how to build the Image object properly and where to get the dirin field from...

**Comment by darafferty** [comment]
I think you can give `img` and `img.indir` to `read_image_from_file()`(`img` is the Image object passed to Op_rmsimage). Something like:

`data, hdr = read_image_from_file(mean_fits_name, img, img.indir)`

Otherwise, looks good to me!

**Comment by cyriltasse** [comment]
@darafferty thanks - i'll give it a try

**Comment by tammojan** [comment]
This was fixed in #43.
