### ISSUE TITLE
Definition of srl catalog and multiple sources 

### ISSUE THREAD

**Issue by cyriltasse** [lofar-astron/PyBDSF#40]
I've made an extration and an `srl` type catalog. Reading the documentation here

http://www.astron.nl/citt/pybdsm/write_catalog.html#definition-of-output-columns

I understand from it the gaussians are groupped - eventually into multiple sources, but then - how can the fields for example `Maj: the FWHM of the major axis of the source, in degrees` can be defined and computed for multiple sources? That's probably a question for @darafferty

**Comment by darafferty** [comment]
There's some info here: http://www.astron.nl/citt/pybdsm/algorithms.html#grouping-of-gaussians-into-sources. Basically, when a source is composed of multiple gaussians, the catalog just gives an indication of the source size but isn't usually too useful beyond that.

**Comment by cyriltasse** [comment]
Thanks @darafferty
