### ISSUE TITLE
Trying to fit at specific positions using src_ra_dec

### ISSUE THREAD

**Issue by ulricharmel** [lofar-astron/PyBDSF#47]
Hi, I get the following error when I use the src_ra_dec option in  *process_image*

File "/home/ulrich/.local/lib/python2.7/site-packages/bdsf/functions.py", line 1999, in make_src_mask
    mask[submask_slice] = submask
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by epolisensky** [comment]
I have run into this same error

**Comment by tjgalvin** [comment]
I fixed this on a local install. At some point numpy started to enforce integer only indices. They used to allow floats to be used which would internally be typecasted to ints. The slicing used at present are floats. I ended editing the in `functions.py` to

`submask_slice = [slice(int(xlo), int(xhi)), slice(int(ylo), int(yhi))]`

and in `islands.py` changing the `__expand_bbox` function to 

`return slice(int(max(0, bbox.start - 1)), int(min(shape, bbox.stop + 1)))`

I can submit a pull request if interested.

**Comment by epolisensky** [comment]
Yes! That fixed worked for me too. I had forgotten about this issue, thanks!

**Comment by tjgalvin** [comment]
There was a final edit I had to `__call__` in `gausfit.py`. When there is a `src_ra_dec` specified but no island was found there is a gaussian generated at the specified position and flagged. The specific changes were

`posn_isl = (int(isl.shape[0]/2.0), int(isl.shape[1]/2.0))`
`posn_img = (int(isl.shape[0]/2.0 + isl.origin[0]), int(isl.shape[1]/2.0 + isl.origin[1]))`

I can submit a pull request if needed.

**Comment by ulricharmel** [comment]
@tjgalvin Yes it is working. Maybe you should make a pull request or update it for the next release. Thanks.
In meantime I will close the issue.

**Comment by tjgalvin** [comment]
Great! Thanks for that!

I had a passing thought. From what I remember of the code if a `src_ra_dec` is set outside the image footprint, I think there is an error thrown. Perhaps the exception should be caught and marked in the catalogue? I was experimenting with using a sky model/list of prior positions  and `src_ra_dec`and this came up. Thoughts?

**Comment by darafferty** [comment]
That's a good idea -- I'll have a look. Maybe we can add a dummy entry to the catalog in these cases or, at the least, give a warning and continue without them...
