### ISSUE TITLE
endless run of PyBDSF during initsubtract-Fast (prefactor)

### ISSUE THREAD

**Issue by adrabent** [lofar-astron/PyBDSF#48]
Hi,

I currently encounter a strange issue while running the initsubtract-Fast pipeline of prefactor.
At step `mask_high` it calls `PyBDSF` via the script `make_clean_mask.py`.

This is the output:

[pipeline.log](https://github.com/lofar-astron/PyBDSF/files/1663598/pipeline.log)

Since one day it does not proceed anymore. (I had another test run last weekend, where it didn't proceed at this stage for more than 3 days). Afterwards I updated PyBDSF to the most recent version, but the problem still persists. I guess it might got stuck in a loop or something.

Cheers,
Alex

**Comment by darafferty** [comment]
Alex, can you send me the image? I will try to debug the problem...

**Comment by gmloose** [comment]
Is this still an issue?

**Comment by adrabent** [comment]
I actually don't recall whether this problem was fixed or not.
Since prefactor is deprecated now I think we can close this issue.
