### ISSUE TITLE
Total flux error issue?

### ISSUE THREAD

**Issue by 1054** [lofar-astron/PyBDSF#50]
Dear PyBDSF developers, 

I'm a user of PyBDSF (PyBDSM) and I'm very happy that PyBDSM works quite well for my millimeter source photometry. I have a question about the total flux error calculation in the source code `"functions.py"`, line 800: 
`
e_tot = pp[0] * sqrt(...)
`

I know that this is according to Condon (1997), but according to Condon (1997)'s equation (42), I would expect:  
`
e_tot = pp[6] * sqrt(...)
`
where `"pp[6]"` should be the total flux, while `"pp[0]"` is the peak flux. 

I found this because I calculated Condon (1997) flux errors by myself according to the equations therein, but found discrepancy here. Then, I've also done Monte Carlo simulations to verify PyBDSM photometry, finding good agreements except for the total flux errors. For sources with very large sizes, e.g., 5 times the beam size, their total flux errors are much smaller than what Monte Carlo simulation suggests, roughly by a factor of `(Peak_flux/Total_flux)`. 

So I think it would be great if you could have a check here! 
And please let me know if I am wrong...

Thank you very much!
With best regards!

**Comment by darafferty** [comment]
Yes, you're quite right -- thank you for reporting this and for looking into it so thoroughly! It should be fixed now in latest master.
