### ISSUE TITLE
Importing error

### ISSUE THREAD

**Issue by anilk991** [lofar-astron/PyBDSF#59]
I have a system of Ubuntu 16.04 LTS, python 2.7.12. I have installed all the requirements for the PyBDSF, but when importing bdsf it gives following error:

import bdsf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rezikoundal/.local/lib/python2.7/site-packages/bdsf-1.8.13-py2.7-linux-x86_64.egg/bdsf/__init__.py", line 19, in <module>
    from collapse import Op_collapse
  File "/home/rezikoundal/.local/lib/python2.7/site-packages/bdsf-1.8.13-py2.7-linux-x86_64.egg/bdsf/collapse.py", line 10, in <module>
    import _cbdsm
ImportError: /home/rezikoundal/.local/lib/python2.7/site-packages/bdsf-1.8.13-py2.7-linux-x86_64.egg/bdsf/_cbdsm.so: undefined symbol: _gfortran_stop_numeric_f08

**Comment by tjuerges** [comment]
That symbol is usually provided by libgfortran.so.  So make sure you have it installed on your system.

**Comment by anilk991** [comment]
How to install libgfortran.so. I looked on web and have installed GCC 7 which according to this link "https://stackoverflow.com/questions/46516394/how-to-install-libgfortran-so-4-on-ubuntu-16-06?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa", contains libgfortran.so.

But still not working.

**Comment by tjuerges** [comment]
I am not familiar with Ubuntu 16.04 and installing GCC7 on it.  If the library is not installed in one of the usual places where the system is looking for dynamically loaded libraries then adding its path to the LD_LIBRARY_PATH environment variable might help.

**Comment by anilk991** [comment]
"LD_LIBRARY_PATH=:/usr/lib/gcc/:/usr/lib/gcc/x86_64-linux-gnu/5:/usr/lib/gcc/x86_64-linux-gnu/5"
I have added path of libfortran.so file to LD_LIBRARY_PATH environment variable yet the error is same.

**Comment by tjuerges** [comment]
Perhaps exporting the environment variable helps?
