### ISSUE TITLE
no python3 support

### ISSUE THREAD

**Issue by gijzelaerr** [lofar-astron/PyBDSF#60]
for example:

```
  src/c++/MGFunction1.cc:44:29: error: ‘PyInt_AsLong’ was not declared in this scope
       m_ndata = n::size(data) - PyInt_AsLong(sum);
                                 ^~~~~~~~~~~~
    src/c++/MGFunction1.cc:44:29: note: suggested alternative: ‘PyLong_AsLong’
       m_ndata = n::size(data) - PyInt_AsLong(sum);
                                 ^~~~~~~~~~~~
                                 PyLong_AsLong
```

**Comment by darafferty** [comment]
I think Python 3 support is being worked on. @tammojan: is that right?

**Comment by tammojan** [comment]
I've checked at NRAO but have not heard back.. So I don't think anyone is working on python3 support for PyBDSF now.

**Comment by mattia-vaccari** [comment]
@darafferty wrote me the following a few weeks back "I am actually working on converting it to Python 3 right now. I hope to have it working soon". Happy to help testing the new code is useful.

**Comment by darafferty** [comment]
Thanks @mattia-vaccari -- I just updated the master branch with Python 3 support, so do please test it and let me know of any issues.

**Comment by darafferty** [comment]
Sorry, version 1.8.15 is still Python 2 only -- there is no released version yet with Python 3 support (I'd like the current master to get tested a bit more before making a new release). Can you try the current master branch instead?

**Comment by mattia-vaccari** [comment]
Thanks, looks like we will have to sort out our boost install first, will keep you posted.

**Comment by darafferty** [comment]
The latest release (v1.9.0) now supports Python 3. Please reopen this issue if there are further problems.
