### ISSUE TITLE
Export CASA image

### ISSUE THREAD

**Issue by ajstewart** [lofar-astron/PyBDSF#72]
When I try to export_image using `img_format = 'casa'`, I get the following error:

```
BDSF [20]: go
---------> go()
ERROR: Error writing CASA image. Use img_format = 'fits' instead.
```

Exporting as a fits works ok. What could cause this as that error message is all that is reported back.

**Comment by ajstewart** [comment]
This was because I did not have casacore loaded in my PATH or LD_LIBRARY_PATH. Perhaps the error message should be changed to reflect that it's simply an import error?

**Comment by darafferty** [comment]
Thanks, changed as suggested -- indeed, the old message wasn't very helpful.
