### ISSUE TITLE
Installation failed: Centos 7.5.1804

### ISSUE THREAD

**Issue by niteshb0804** [lofar-astron/PyBDSF#79]
Are there any additional steps to be taken care of other than the ones mentioned on the pybdsf github
page for installation on Centos 7.5.1804 ?
I am getting the following error on trying the mentioned procedure for installation..
Output:

----snip

/usr/lib64/python3.4/site-packages/numpy/core/include/numpy/__multiarray_api.h:1547:151: note: in expansion of macro ‘NUMPY_IMPORT_ARRAY_RETVAL’
     #define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NUMPY_IMPORT_ARRAY_RETVAL; } }
^
    src/c++/cbdsm_main.cc:20:3: note: in expansion of macro ‘import_array’
       import_array();
       ^
    error: Command "g++ -pthread -Wno-unused-result -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/c++ -I/usr/lib64/python3.4/site-packages/numpy/core/include -I/usr/include/python3.4m -c src/c++/cbdsm_main.cc -o build/temp.linux-x86_64-3.4/src/c++/cbdsm_main.o -MMD -MF build/temp.linux-x86_64-3.4/src/c++/cbdsm_main.o.d" failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-ejlv_g5h/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-yj3qlvjj/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-ejlv_g5h/

**Comment by darafferty** [comment]
Hmm, it looks like you're trying to use Python 3, which is currently not supported (I have it mostly working on the python3 branch, so I hope support will come soon). Could you try compiling with python 2.7?

**Comment by niteshb0804** [comment]
Thanks, it worked with python 2.7.
