### ISSUE TITLE
Header 

### ISSUE THREAD

**Issue by 960801** [lofar-astron/PyBDSF#82]
When I run pyBDSF on my Ubuntu 18.04 and I input the name of the file and type go it returns the error bellow :
"AttributeError: 'Header' object has no attribute  'ascard'" 
How do I deal with this type of error? 
Thank you!

**Comment by darafferty** [comment]
Hmm -- 'ascard' is not used anywhere in PyBDSF, so the error must occur in one of the dependencies (probably astropy, pyfits, or pywcs). Make sure you have astropy installed and that it is the latest version.

**Comment by 960801** [comment]
The problem was as you mentioned, i just installed astropy and it works now.
Thank you very much for helping me
👍
