### ISSUE TITLE
Aperture fluxes

### ISSUE THREAD

**Issue by epolisensky** [lofar-astron/PyBDSF#83]
There is an issue with the slice indices in the aperture flux calculation, lines 1942 & 1943 in functions.py. This is the same fix as issue #47:

    aper_im = ch0[int(xlo):int(xhi), int(ylo):int(yhi)] - mean[int(xlo):int(xhi), int(ylo):int(yhi)]
    aper_rms = rms[int(xlo):int(xhi), int(ylo):int(yhi)]

**Comment by darafferty** [comment]
Thanks -- I'm not sure why the indices are not integers here (perhaps the elements of ch0.shape are not integers?), but in any case I committed your fix to the current master.
