### ISSUE TITLE
writeto() type error

### ISSUE THREAD

**Issue by tanita-rh** [lofar-astron/PyBDSF#86]
For both write_catalog and export_image give me the error "TypeError: writeto() got an unexpected keyword argument 'overwrite'", and the command does not run. Please advise me on solutions to this. Thank you!

**Comment by darafferty** [comment]
Do you have astropy installed, and if so, what is its version? I think the "overwrite" argument was added in v1.3.

**Comment by tanita-rh** [comment]
I have a lower version (1.1.1), it's on the server. I will work with the system admin. Thank you so much for your help!

**Comment by darafferty** [comment]
OK, thanks -- PyBDSF shouldn't require a newer astropy, but I see that we don't check the version when using the overwrite argument. Updating astropy should fix the problem, but I will also add a check so that older versions work too.
