### ISSUE TITLE
issue with scipy convolve2d in blanking check

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/PyBDSF#87]
scipy issue 8814 (https://github.com/scipy/scipy/issues/8814) is affecting some of my nodes -- only certain processor types and I think only since a recent scipy upgrade.

The code that triggers it is in `collapse.py` where a check for data affected by the AWImager blanking bug is forced if the image has 'restored' in its name. I don't know how many people are still using unblanked images from AWImager... maybe one option would just be to kill off this code? At the moment I have added an option force_no_blank_check, defaulting to False, which if set to True bypasses the code that uses convolve2d and allows execution to continue. I can make a PR for this if it's felt to be the best solution.

**Comment by mhardcastle** [comment]
Sorry to push on this, but can we decide whether we could kill off the AWImager blanking warning (and so remove the scipy.convolve2d call) or whether I can add an option to bypass it? Happy to provide PRs for either.

Currently I can't push my development ddf-pipeline because it needs to contain a workround for this issue which doesn't work with anyone else's version of PyBDSF...

**Comment by darafferty** [comment]
Yes, I think it would be fine to remove the code -- can you submit the PR for this? I will merge it asap.
