### ISSUE TITLE
Old image headers renamed

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/PyBDSF#89]
Commit 4fc960aad8a02a2737443d85e486b0bffcb84a72 changes the behaviour wrt the image FITS headers -- they used to be appended prefixed with I_ as in PR #53, now they are comments. Is this an intentional, permanent change? Because if so I need to fix the code in ddf-pipeline that depends on it.

**Comment by darafferty** [comment]
Yes, Huib Intema pointed out that prepending "I_" meant that some or the resulting keywords were longer than the allowed 8 characters of the FITS standard. I didn't realize this would break the ddf-pipeline -- sorry about that. I also notice now that the "I_" prefix is not used in Huib's fix -- would it be helpful to add it?

**Comment by mhardcastle** [comment]
No, it's OK. I've already written some code to go in DDFacet to parse the comments and pull the relevant keywords out of there if they exist, and from PyBDSF's point of view I can see it's cleaner this way. Just wanted to check that it was intentional since I didn't see an issue related to the change.
