### ISSUE TITLE
Setup failed: fortran error

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/PyBDSF#9]
f2py on my system complains about the line

``parameter (rad=180.d0/pi)``

in ``src/fortran/constants.inc``. It is fine with

``parameter (rad=57.29577951308232)``

It's been so long since I've done anything with Fortran that I can't remember whether an expression is valid in a parameter statement, but anyway, simple fix.

**Comment by tammojan** [comment]
@darafferty, if you write 'fixes #9' instead of just '#9' in the commit message, the issue closes automatically. See https://help.github.com/articles/closing-issues-via-commit-messages/
