### ISSUE TITLE
quiet output not working

### ISSUE THREAD

**Issue by amisk** [lofar-astron/PyBDSF#99]
Hi,

I'm running this in a python script:
`sources = bdsf.process_image(filename,quiet=True)`

But it is not quiet... am I missing something?

**Comment by bruzewskis** [comment]
Based on my own experimentation, the effects of quiet=True seem somewhat obscure. Attached are two examples on the same file, one quiet the other not. The only noticeable difference in this case is that the loading bar in "Fitting islands with Gaussians" was removed, as well as the warning at the end. 

<img width="770" alt="Screen Shot 2019-09-24 at 15 59 26" src="https://user-images.githubusercontent.com/22014621/65553837-04bec900-dee5-11e9-881a-0f817b751ebf.png">
<img width="774" alt="Screen Shot 2019-09-24 at 16 00 09" src="https://user-images.githubusercontent.com/22014621/65553838-05575f80-dee5-11e9-8752-465cd55dd697.png">

**Comment by darafferty** [comment]
Ah, indeed the `quiet` argument was not being passed along properly. It should be fixed now in the latest master.
